### ISSUE TITLE
Crash while pairing

### ISSUE THREAD

**Issue by mrstegeman** [tim-hellhake/sonos-adapter#15]
```
2020-01-19 22:29:16.146 ERROR  : sonos: dgram.js:638
2020-01-19 22:29:16.147 ERROR  : sonos:     throw new errors.Error('ERR_SOCKET_DGRAM_NOT_RUNNING');
2020-01-19 22:29:16.148 ERROR  : sonos:     ^
2020-01-19 22:29:16.149 ERROR  : sonos:
2020-01-19 22:29:16.149 ERROR  : sonos: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
2020-01-19 22:29:16.150 ERROR  : sonos:     at Socket._healthCheck (dgram.js:638:11)
2020-01-19 22:29:16.151 ERROR  : sonos:     at Socket.close (dgram.js:516:8)
2020-01-19 22:29:16.152 ERROR  : sonos:     at DeviceDiscovery.destroy (/home/pi/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/deviceDiscovery.js:82:15)
2020-01-19 22:29:16.152 ERROR  : sonos:     at SonosAdapter.cancelPairing (/home/pi/.mozilla-iot/addons/sonos-adapter/adapter.js:86:30)
2020-01-19 22:29:16.153 ERROR  : sonos:     at AddonManagerProxy.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:316:17)
2020-01-19 22:29:16.154 ERROR  : sonos:     at IpcSocket.onData (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/ipc.js:171:10)
2020-01-19 22:29:16.154 ERROR  : sonos:     at emitOne (events.js:116:13)
2020-01-19 22:29:16.155 ERROR  : sonos:     at Socket.emit (events.js:211:7)
2020-01-19 22:29:16.156 ERROR  : sonos:     at addChunk (_stream_readable.js:263:12)
2020-01-19 22:29:16.156 ERROR  : sonos:     at readableAddChunk (_stream_readable.js:250:11)
2020-01-19 22:29:16.161 INFO   : Plugin: sonos-adapter died, code = 1 restarting after 0
```

**Comment by tim-hellhake** [comment]
That's strange.
I added and removed my sonos multiple times without any errors.
Can you reproduce the error?
,0,,

**Comment by tim-hellhake** [comment]
That's strange.
I added and removed my sonos multiple times without any errors.
Can you reproduce the error?

**Comment by mrstegeman** [comment]
I've never seen it before and cannot reproduce. Feel free to close, I just wanted to note it at least. It could easily be fixed by wrapping the content of `cancelPairing()` in a try/catch.
