### ISSUE TITLE
add IP address to Sonos config if can't be found?

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/sonos-adapter#9]
Although I didn't change anything on my local network, for some reason the Sonos speaker went "offline" from yesterday to today. I tried power cycling all sorts of things, including the speaker. I disabled/enabled the Sonos add-on. The speaker IS connected to my Wi-Fi router, and I can control it from my smartphone, and I can play streamed Internet radio through it, using my smartphone as controller. I tried removing it from the gateway Things page, since I have needed to do that anytime my Google Home receives a new IP address. However, my WebThings Gateway doesn't find the Sonos at all anymore during a scan. The log shows:
```sonos: setName() is deprecated. Please use setTitle().
2019-08-27 11:17:11.595 ERROR  : sonos: ReferenceError: URL is not defined
2019-08-27 11:17:11.597 ERROR  : sonos:     at zonesArray.forEach (/home/pi/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/sonos.js:369:19)
2019-08-27 11:17:11.599 ERROR  : sonos:     at Array.forEach (<anonymous>)
2019-08-27 11:17:11.600 ERROR  : sonos:     at Sonos.getAllGroups (/home/pi/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/sonos.js:360:14)
2019-08-27 11:17:11.602 ERROR  : sonos:     at <anonymous>
2019-08-27 11:17:11.604 ERROR  : sonos:     at process._tickCallback (internal/process/next_tick.js:189:7)```

**Comment by kgiori** [comment]
There was one additional line in the log that might help debug:
```
2019-09-04 11:46:27.735 INFO   : sonos: setName() is deprecated. Please use setTitle().
2019-09-04 11:46:28.093 ERROR  : sonos: ReferenceError: URL is not defined
2019-09-04 11:46:28.097 ERROR  : sonos:     at zonesArray.forEach (/home/pi/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/sonos.js:369:19)
2019-09-04 11:46:28.100 ERROR  : sonos:     at Array.forEach (<anonymous>)
2019-09-04 11:46:28.102 ERROR  : sonos:     at Sonos.getAllGroups (/home/pi/.mozilla-iot/addons/sonos-adapter/node_modules/sonos/lib/sonos.js:360:14)
2019-09-04 11:46:28.105 ERROR  : sonos:     at <anonymous>
2019-09-04 11:46:28.107 ERROR  : sonos:     at process._tickCallback (internal/process/next_tick.js:189:7)```

**Comment by mrstegeman** [comment]
This is actually unrelated to the IP address. See upstream issue referenced above.
